"""The 5.0.0 generated file format: header, no treestamps_config, defaults fill."""

import logging
from pathlib import Path

import pytest

from tests import PROGRAM
from tests.integration.base_test import BaseTestDir
from treestamps.grove import Grovestamps, GrovestampsConfig
from treestamps.tree import Treestamps
from treestamps.tree.config import TreestampsConfig

__all__ = ()

PROGRAM_NAME = f"{PROGRAM}-tests-generated-format"
TS_FN = f".{PROGRAM_NAME}_treestamps.yaml"
WAL_FN = f".{PROGRAM_NAME}_treestamps.wal.yaml"
STAMP_TS = 100.0
KEYS = ("quality", "new_flag")
DEFAULTS = {"quality": 1, "new_flag": False}


class TestGeneratedFormat:
    """Header comments and the removed treestamps_config block."""

    def _config(self, path: Path, **kwargs) -> TreestampsConfig:
        """Build a tree config with a program config."""
        kwargs.setdefault("program_config", {"quality": 1})
        return TreestampsConfig(
            PROGRAM_NAME, path=path, program_config_keys=KEYS, **kwargs
        )

    def test_header_written_to_snapshot_and_wal(self, tmp_path: Path) -> None:
        """Both generated files lead with an explanatory comment header."""
        ts = Treestamps(self._config(tmp_path, note=("Safe to delete.",)))
        ts.set(tmp_path / "file", STAMP_TS)
        wal_text = (tmp_path / WAL_FN).read_text()
        ts.dumpf()
        snapshot_text = (tmp_path / TS_FN).read_text()

        for text in (snapshot_text, wal_text):
            assert text.startswith("# @generated by treestamps ")
            assert PROGRAM_NAME in text.splitlines()[0]
            assert "do not edit" in text
            assert "# Safe to delete." in text

    def test_header_is_compare_invisible(self, tmp_path: Path) -> None:
        """Comments never reach the loader, so a note change invalidates nothing."""
        ts = Treestamps(self._config(tmp_path, note=("First note.",)))
        ts.set(tmp_path / "file", STAMP_TS)
        ts.dumpf()

        ts2 = Treestamps(self._config(tmp_path, note=("A completely different note.",)))
        ts2.loadf_tree()
        assert ts2.get(tmp_path / "file") == STAMP_TS

    def test_treestamps_config_block_not_written(self, tmp_path: Path) -> None:
        """The redundant treestamps_config block is gone as of 5.0.0."""
        ts = Treestamps(self._config(tmp_path, ignore=("*.tmp",), symlinks=False))
        ts.set(tmp_path / "file", STAMP_TS)
        # dumpf deletes the WAL, so read it while it still exists.
        wal_text = (tmp_path / WAL_FN).read_text()
        ts.dumpf()
        assert "treestamps_config" not in (tmp_path / TS_FN).read_text()
        assert "treestamps_config" not in wal_text

    def test_legacy_file_with_treestamps_config_still_loads(
        self, tmp_path: Path
    ) -> None:
        """Files written before 5.0.0 carry the block; it must be popped, not parsed."""
        (tmp_path / TS_FN).write_text(
            """config:
  quality: 1
treestamps_config:
  ignore: !!set {}
  symlinks: true
file: 100.0
"""
        )
        ts = Treestamps(self._config(tmp_path, program_config_defaults=DEFAULTS))
        ts.loadf_tree()
        assert ts.get(tmp_path / "file") == STAMP_TS
        # The block must not have been mistaken for a timestamp entry.
        assert ts.get(tmp_path / "treestamps_config") is None

    def test_added_key_with_default_value_keeps_stamps(
        self, tmp_path: Path, caplog: pytest.LogCaptureFixture
    ) -> None:
        """A newly recorded key at its default must not invalidate old files."""
        caplog.set_level(logging.WARNING, logger="treestamps.tree.load")
        # Written by an older version that did not know about new_flag.
        (tmp_path / TS_FN).write_text("config:\n  quality: 1\nfile: 100.0\n")
        ts = Treestamps(
            self._config(
                tmp_path,
                program_config={"quality": 1, "new_flag": False},
                program_config_defaults=DEFAULTS,
            )
        )
        ts.loadf_tree()
        assert ts.get(tmp_path / "file") == STAMP_TS
        assert not caplog.records

    def test_added_key_with_other_value_invalidates(
        self, tmp_path: Path, caplog: pytest.LogCaptureFixture
    ) -> None:
        """A newly recorded key set to a non-default value still invalidates."""
        caplog.set_level(logging.WARNING, logger="treestamps.tree.load")
        (tmp_path / TS_FN).write_text("config:\n  quality: 1\nfile: 100.0\n")
        ts = Treestamps(
            self._config(
                tmp_path,
                program_config={"quality": 1, "new_flag": True},
                program_config_defaults=DEFAULTS,
            )
        )
        ts.loadf_tree()
        assert ts.get(tmp_path / "file") is None
        message = caplog.records[0].getMessage()
        assert "config mismatch" in message
        assert "new_flag" in message

    def test_key_labels_rename_keys_in_warnings(
        self, tmp_path: Path, caplog: pytest.LogCaptureFixture
    ) -> None:
        """Internal key names are replaced by friendly labels in mismatch warnings."""
        caplog.set_level(logging.WARNING, logger="treestamps.tree.load")
        (tmp_path / TS_FN).write_text("config:\n  quality: 9\nfile: 100.0\n")
        ts = Treestamps(
            self._config(
                tmp_path,
                program_config_key_labels={"quality": "the quality option"},
            )
        )
        ts.loadf_tree()
        message = caplog.records[0].getMessage()
        assert "the quality option" in message
        assert "quality:" not in message

    def test_wal_replay_honors_defaults_fill(self, tmp_path: Path) -> None:
        """WAL headers go through the same comparison as snapshots."""
        ts = Treestamps(self._config(tmp_path))
        ts.set(tmp_path / "file", STAMP_TS)
        assert ts._wal is not None
        ts._wal.flush()

        # Simulate a crash before dumpf, then reload with an added key.
        ts2 = Treestamps(
            self._config(
                tmp_path,
                program_config={"quality": 1, "new_flag": False},
                program_config_defaults=DEFAULTS,
            )
        )
        ts2.loadf_tree()
        assert ts2.get(tmp_path / "file") == STAMP_TS


class TestTreeConfigFactory(BaseTestDir):
    """Per-tree configs built by a factory."""

    def test_factory_builds_per_tree_configs(self) -> None:
        """Each tree may record its own program config."""
        first = self.tmp_root / "first"
        second = self.tmp_root / "second"
        first.mkdir()
        second.mkdir()

        def factory(top_path: Path) -> TreestampsConfig:
            return TreestampsConfig(
                PROGRAM_NAME,
                path=top_path,
                program_config={"quality": 1 if top_path.name == "first" else 2},
                program_config_keys=KEYS,
            )

        config = GrovestampsConfig(
            PROGRAM_NAME, paths=(first, second), tree_config_factory=factory
        )
        gs = Grovestamps(config)
        assert gs[first].set(first / "f", STAMP_TS) == STAMP_TS
        assert gs[second].set(second / "f", STAMP_TS) == STAMP_TS
        gs.dumpf()

        assert "quality: 1" in (first / TS_FN).read_text()
        assert "quality: 2" in (second / TS_FN).read_text()

    def test_factory_none_skips_tree(self) -> None:
        """Returning None creates no store and no stamp file for that tree."""
        on = self.tmp_root / "on"
        off = self.tmp_root / "off"
        on.mkdir()
        off.mkdir()

        def factory(top_path: Path) -> TreestampsConfig | None:
            if top_path.name == "off":
                return None
            return TreestampsConfig(PROGRAM_NAME, path=top_path)

        config = GrovestampsConfig(
            PROGRAM_NAME, paths=(on, off), tree_config_factory=factory
        )
        gs = Grovestamps(config)
        assert set(gs) == {on}
        assert gs[on].set(on / "f", STAMP_TS) == STAMP_TS
        gs.dumpf()
        assert (on / TS_FN).exists()
        assert not (off / TS_FN).exists()
